spring:
  application:
    name: mentir-file-operation-service
  data:
    mongodb:
      uri: mongodb+srv://admin:1@cluster0.qylc2.mongodb.net/fileDB?retryWrites=true&w=majority
#      authentication-database: admin
#      username: root
#      password: root
#      database: fileDB
#      port: 27017
#      host: localhost
  servlet:
    multipart:
      max-file-size: 20000KB
      max-request-size: 20000KB
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
feign:
  client:
    url:
      userService: ${USER_SERVICE:http://localhost:8082/}