apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service
  labels:
    app: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - name: security-service
          image: tankietxm/security-service:1.0.0
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_SERVER
              value: http://eureka-server:8761/eureka
            - name: USER_SERVICE
              value: http://user-service:8082/
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:
    security-service
  labels:
    app: security-service
spec:
  selector:
    app: security-service
  ports:
    - port: 8085
  type: ClusterIP