apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: tankietxm/user-service:1.0.0
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_SERVER
              value: http://eureka-server:8761/eureka
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:
    user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8082
  type: ClusterIP